version: '3'

services:

  traefik:
    image: traefik:v2.11
    container_name: traefik
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ~/traefik/config/traefik.yml:/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_net

  odoo:
    container_name: odoo
    image: odoo:17
    ports:
      - 8069:8069
    volumes:
      - ~/odoo.conf:/etc/odoo/odoo.conf
    labels:
      - traefik.enable=true
      - "traefik.http.routers.odoo.rule=Host(`odoo.example.com`)"
      - traefik.http.routers.odoo.entrypoints=web
    restart: always
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true



            